### ISSUE TITLE
Rebuild needed for icu 59

### ISSUE THREAD

**Issue by beojan** [qutebrowser/qt-debug-pkgbuild#12]
Arch have updated the icu package, so this needs a rebuild.

**Comment by The-Compiler** [comment]
Yup - I usually follow up with a new version on the same day as the Arch package gets updated, but it took a bit longer this time because of bigger updates in the qt5-base and pyqt packages which required updates to the script.

They're building now, and if everything goes well they'll be up in an hour or two. If not, I'm going to take another look tomorrow morning.

**Comment by The-Compiler** [comment]
Looks like it worked!
