### ISSUE TITLE
cannot open any Qt5 app: "error while loading shared libraries: libicui18n.so.64: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by glaubersm** [qutebrowser/qt-debug-pkgbuild#25]
Hi
I have installed your packages on my Arch Linux with the following command:

`sudo pacman -S qt5-base-debug qt5-declarative-debug qt5-graphicaleffects-debug qt5-imageformats-debug qt5-location-debug qt5-multimedia-debug qt5-quickcontrols-debug qt5-quickcontrols2-debug qt5-script-debug qt5-sensors-debug qt5-speech-debug qt5-svg-debug qt5-tools-debug qt5-wayland-debug qt5-webchannel-debug qt5-webengine-debug qt5-websockets-debug qt5-x11extras-debug qt5-xmlpatterns-debug qt5-webkit-debug qt5-translations-debug qt5-networkauth-debug
`

Terminal shows this error when I try to open any Qt5 app:
`error while loading shared libraries: libicui18n.so.64: cannot open shared object file: No such file or directory`

**Comment by The-Compiler** [comment]
Looks like some packages need a rebuild due to icu 65...

I pushed the necessary changes in ebf466e891ec983ccbab070b5e3803a1cebf72b4 but it'll take me some more time until I can build the packages. Unfortunately, the machine I used so far is inaccessible and will likely be until April (due to the hackerspace where it was hosted moving out). I'll see if I can find some alternative solution, unfortunately building QtWebKit/QtWebEngine needs a quite powerful machine and takes some time.

**Comment by glaubersm** [comment]
Thanks for your interest on this issue. :)

**Comment by The-Compiler** [comment]
FWIW I decided to wait until Qt 5.14 is out of `[testing]` (which hopefully is soon) and then rent some beefy cloud instance to rebuild the packages.

**Comment by The-Compiler** [comment]
Turns out Google Cloud Engine only lets me rent 16 cores without requesting a manual quota increase - so that's what I ended up doing, currently building the packages. There are some more manual steps involved than usual, so let's see how things will go.

**Comment by The-Compiler** [comment]
Looks like that worked (more or less) - I uploaded Qt 5.14 packages!
